/*
	Conrad 'Condzi' Kubacki 2017
	https://github.com/condzi
*/

#include <Core/Settings.hpp>

namespace con {

BEGIN_SETTINGS_CONTENT_DEF( SETTINGS_DEFAULT_ENGINE )
SETTING_DEF( "WINDOW", "FPS", "60" ),
SETTING_DEF( "WINDOW", "SIZE_X", "1280" ),
SETTING_DEF( "WINDOW", "SIZE_Y", "720" ),

SETTING_DEF( "AUDIO", "MASTER_VOLUME", "100" ),
SETTING_DEF( "AUDIO", "MUSIC_VOLUME", "100" ),
SETTING_DEF( "AUDIO", "SOUND_VOLUME", "100" ),

SETTING_DEF( "PHYSIC", "UPS", "60" )
END_SETTINGS_CONTENT_DEF();

BEGIN_SETTINGS_CONTENT_DEF( SETTINGS_DEFAULT_GAME )
SETTING_DEF( "DEFAULT", "NAME", "SpaceY" )
END_SETTINGS_CONTENT_DEF();
}